name: Shell Commands

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: Echo A String
        run: echo "Hello World"
      - name: Multi-Line Script
        run: |
          node -v
          npm -v
      - name: Python Command
        run: |
          import platform
          print(platform.processor())
        shell: python

  run-windows-commands:
    runs-on: windows-latest
    needs: ["run-shell-command"]
    steps:
      - name: Directory PowerShell
        run: Get-Location
      - name: Directory Bash
        run: pwd
        shell: bash
        
  secret_sauce:
    runs-on: ubuntu-latest
    steps:
      - name: Printing Secrets
        run: |
          touch /tmp/my_secret
          echo printf "$DEV_ENV" >> /tmp/my_secret
          cat /tmp/my_secret
        shell: bash
        env:
          DEV_ENV: ${{ secrets.MY_SECRET }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: DEV_ENV_FILE
          path: tmp/my_secret
